export const MAIN_PAGE_ROUTE = '/'
// export const APARTMENTS_ROUTE = '/apartments'
// export const PARKING_ROUTE = '/parking'
// export const STORE_ROOMS_ROUTE = '/storeRooms'
// export const STORAGE_FACILITIES_ROUTE = '/storageFacilities'
export const GALLERY_ROUTE = '/gallery'